### ISSUE TITLE
Names for lookup tables are tedious

### ISSUE THREAD

**Issue by pbchase** [PFWhite/QUAIL#1]
Having written queries against quail tables I find the names of the lookup tables tedious.  They are all prefixed with "radio_", "checkbox_" or "dropdown_".  It's a distinction that's not terribly valuable to me. When I have a few 100 of these tables, it's hard to locate the one I need. The task is made no easier by the prefix in the name.  I don't know or care whether a field had a radio button or a dropdown. While a checkbox could be multi_valued and that would change the way I write my query, I don't much care. I'd much rather not have to think,"What field type was that?".

Could we move to a single prefix of "lu_" for all of these tables? That would help me separate a certain form of chaff from thew wheat without having to make any finer distinctions.

**Comment by PFWhite** [comment]
This has been fixed. We removed the prefix for the lookup tables. You will be able to find the code that does this in the pull request into the ctsit/quail call "updates for honeyguide"

**Comment by pbchase** [comment]
Thanks, Patrick!
